/**
 * Every distinct transaction-type label in the real exports, with one verbatim row per label.
 *
 * Generated by reading the six source files in `listadoTransacciones` — not transcribed. The counts
 * are the label's frequency in its file and are asserted, so a re-export that renames or drops a
 * label fails here rather than silently at ingestion. `headers` is the source's own header row, which
 * is what lets the net drive the real column mapper instead of a hand-written mapping.
 */
export interface SourceLabelSample {
  readonly label: string;
  readonly count: number;
  readonly row: Readonly<Record<string, string>>;
}

export interface SourceVocabulary {
  readonly source: string;
  readonly market: 'spot' | 'futures';
  readonly typeColumn: string;
  readonly headers: readonly string[];
  readonly labels: readonly SourceLabelSample[];
}

export const SOURCE_VOCABULARIES: readonly SourceVocabulary[] = [
  {
    "source": "kraken_spot.csv",
    "market": "spot",
    "typeColumn": "type",
    "headers": [
      "txid",
      "refid",
      "time",
      "type",
      "subtype",
      "aclass",
      "subclass",
      "asset",
      "wallet",
      "amount",
      "fee",
      "balance"
    ],
    "labels": [
      {
        "label": "deposit",
        "count": 11,
        "row": {
          "txid": "LCKZLQ-KHWZX-5GMPCU",
          "refid": "FTNGi1e-CopBTGbtrN5Zrrbv8RDI2R",
          "time": "2025-09-16 12:06:58",
          "type": "deposit",
          "subtype": "",
          "aclass": "currency",
          "subclass": "fiat",
          "asset": "EUR",
          "wallet": "spot / main",
          "amount": "50.0000",
          "fee": "0",
          "balance": "50.0000"
        }
      },
      {
        "label": "trade",
        "count": 20,
        "row": {
          "txid": "LASZIL-2N6LK-FPQMDU",
          "refid": "TTE7DJ-SLH4A-HWU24P",
          "time": "2025-09-19 01:38:34",
          "type": "trade",
          "subtype": "tradespot",
          "aclass": "currency",
          "subclass": "fiat",
          "asset": "EUR",
          "wallet": "spot / main",
          "amount": "-50.0000",
          "fee": "0",
          "balance": "0.0000"
        }
      },
      {
        "label": "withdrawal",
        "count": 2,
        "row": {
          "txid": "LEYUHY-CLZ3G-BKQDT3",
          "refid": "FTkEI63-uLHFjQyuJjheYq18oDiN2K",
          "time": "2025-11-10 15:48:07",
          "type": "withdrawal",
          "subtype": "",
          "aclass": "currency",
          "subclass": "crypto",
          "asset": "SOL",
          "wallet": "spot / main",
          "amount": "-0.0060000000",
          "fee": "0.0050000000",
          "balance": "0.0097713000"
        }
      },
      {
        "label": "transfer",
        "count": 1,
        "row": {
          "txid": "LKP7I5-DULS6-6XDQDC",
          "refid": "FTHwm6B-RkMQ20mb9KDTRCCRG0ZR4m",
          "time": "2026-01-16 15:41:18",
          "type": "transfer",
          "subtype": "spottofutures",
          "aclass": "currency",
          "subclass": "fiat",
          "asset": "EUR",
          "wallet": "spot / main",
          "amount": "-200.0000",
          "fee": "0",
          "balance": "2.5205"
        }
      }
    ]
  },
  {
    "source": "bitvavo_spot.csv",
    "market": "spot",
    "typeColumn": "Type",
    "headers": [
      "Timezone",
      "Date",
      "Time",
      "Type",
      "Currency",
      "Amount",
      "Quote Currency",
      "Quote Price",
      "Received / Paid Currency",
      "Received / Paid Amount",
      "Fee currency",
      "Fee amount",
      "Status",
      "Transaction ID",
      "Address"
    ],
    "labels": [
      {
        "label": "withdrawal",
        "count": 6,
        "row": {
          "Timezone": "Europe/Madrid",
          "Date": "2026-02-07",
          "Time": "10:19:39",
          "Type": "withdrawal",
          "Currency": "XRP",
          "Amount": "-439.55",
          "Quote Currency": "",
          "Quote Price": "",
          "Received / Paid Currency": "",
          "Received / Paid Amount": "",
          "Fee currency": "XRP",
          "Fee amount": "0",
          "Status": "Completed",
          "Transaction ID": "5a68d802-7105-46d9-b314-8fd5fbd731f8",
          "Address": "rp6huNdpgV7jKTnkiH5ZtmNJn5mezrLtcw"
        }
      },
      {
        "label": "deposit",
        "count": 23,
        "row": {
          "Timezone": "Europe/Madrid",
          "Date": "2026-02-05",
          "Time": "22:42:54",
          "Type": "deposit",
          "Currency": "EUR",
          "Amount": "500",
          "Quote Currency": "",
          "Quote Price": "",
          "Received / Paid Currency": "",
          "Received / Paid Amount": "",
          "Fee currency": "EUR",
          "Fee amount": "0",
          "Status": "Completed",
          "Transaction ID": "7a466c8e-4e56-4e4c-9f29-0c0c34a68003",
          "Address": "ES13***47"
        }
      },
      {
        "label": "buy",
        "count": 12,
        "row": {
          "Timezone": "Europe/Madrid",
          "Date": "2026-02-05",
          "Time": "16:29:01.408",
          "Type": "buy",
          "Currency": "ETH",
          "Amount": "0.30338",
          "Quote Currency": "EUR",
          "Quote Price": "1645",
          "Received / Paid Currency": "EUR",
          "Received / Paid Amount": "-499.81",
          "Fee currency": "EUR",
          "Fee amount": "0.7499",
          "Status": "Completed",
          "Transaction ID": "a00b3738-8d5e-4cee-b074-33a3d074ff77",
          "Address": ""
        }
      },
      {
        "label": "campaign_new_user_incentive",
        "count": 1,
        "row": {
          "Timezone": "Europe/Madrid",
          "Date": "2025-09-30",
          "Time": "10:10:36",
          "Type": "campaign_new_user_incentive",
          "Currency": "EUR",
          "Amount": "10",
          "Quote Currency": "",
          "Quote Price": "",
          "Received / Paid Currency": "",
          "Received / Paid Amount": "",
          "Fee currency": "",
          "Fee amount": "",
          "Status": "Completed",
          "Transaction ID": "616fb4b8-dc68-4591-8ef3-42a902093585",
          "Address": ""
        }
      }
    ]
  },
  {
    "source": "bitunix_spot.csv",
    "market": "spot",
    "typeColumn": "Label",
    "headers": [
      "Date (UTC)",
      "Label",
      "Outgoing Asset",
      "Outgoing Amount",
      "Incoming Asset",
      "Incoming Amount",
      "Fee Asset",
      "Fee Amount",
      "Trx. ID",
      "Comment"
    ],
    "labels": [
      {
        "label": "Deposit",
        "count": 2,
        "row": {
          "Date (UTC)": "2025-12-13 12:07:06",
          "Label": "Deposit",
          "Outgoing Asset": "",
          "Outgoing Amount": "0",
          "Incoming Asset": "ADA",
          "Incoming Amount": "4.5",
          "Fee Asset": "",
          "Fee Amount": "0",
          "Trx. ID": "T0009",
          "Comment": "Chain Deposit"
        }
      },
      {
        "label": "Withdraw",
        "count": 1,
        "row": {
          "Date (UTC)": "2025-12-13 22:03:31",
          "Label": "Withdraw",
          "Outgoing Asset": "ADA",
          "Outgoing Amount": "546.844684",
          "Incoming Asset": "",
          "Incoming Amount": "0",
          "Fee Asset": "ADA",
          "Fee Amount": "1",
          "Trx. ID": "T0010",
          "Comment": "On-chain Withdraw"
        }
      }
    ]
  },
  {
    "source": "tangem_activacion_xrp.csv",
    "market": "spot",
    "typeColumn": "Type",
    "headers": [
      "Date",
      "Type",
      "Asset",
      "Amount",
      "Fee",
      "Notes"
    ],
    "labels": [
      {
        "label": "WALLET_ACTIVATION",
        "count": 1,
        "row": {
          "Date": "2025-06-03 10:01:00 UTC",
          "Type": "WALLET_ACTIVATION",
          "Asset": "XRP",
          "Amount": "1.0",
          "Fee": "0.0",
          "Notes": "Tangem Base Reserve"
        }
      }
    ]
  },
  {
    "source": "kraken_futures.csv",
    "market": "futures",
    "typeColumn": "type",
    "headers": [
      "uid",
      "dateTime",
      "account",
      "type",
      "symbol",
      "contract",
      "change",
      "new balance",
      "new average entry price",
      "trade price",
      "mark price",
      "funding rate",
      "realized pnl",
      "fee",
      "realized funding",
      "collateral",
      "conversion spread percentage",
      "liquidation fee",
      "position uid"
    ],
    "labels": [
      {
        "label": "futures trade",
        "count": 598,
        "row": {
          "uid": "c0e50358-8012-438b-9925-3d49b5371b3a",
          "dateTime": "2026-02-08 16:42:52",
          "account": "flex",
          "type": "futures trade",
          "symbol": "usd",
          "contract": "pf_xrpusd",
          "change": "-1.45480000000",
          "new balance": "0.00000000000",
          "new average entry price": "",
          "trade price": "1.42318000000000000000",
          "mark price": "1.42372579167000000000",
          "funding rate": "-0.000028384605269555",
          "realized pnl": "-1.39220000000",
          "fee": "0.06260000000",
          "realized funding": "",
          "collateral": "",
          "conversion spread percentage": "",
          "liquidation fee": "",
          "position uid": ""
        }
      },
      {
        "label": "conversion",
        "count": 314,
        "row": {
          "uid": "f0b423a1-d660-4a2d-90f5-ff35ba951d4a",
          "dateTime": "2026-02-08 16:42:52",
          "account": "flex",
          "type": "conversion",
          "symbol": "usd",
          "contract": "",
          "change": "1.45480000000",
          "new balance": "1.45480000000",
          "new average entry price": "",
          "trade price": "",
          "mark price": "",
          "funding rate": "",
          "realized pnl": "",
          "fee": "",
          "realized funding": "",
          "collateral": "",
          "conversion spread percentage": "",
          "liquidation fee": "",
          "position uid": ""
        }
      },
      {
        "label": "funding rate change",
        "count": 167,
        "row": {
          "uid": "083ab228-dee6-4f25-aa6b-ba8e47e46ece",
          "dateTime": "2026-02-08 16:00:00",
          "account": "flex",
          "type": "funding rate change",
          "symbol": "usd",
          "contract": "pf_xrpusd",
          "change": "0.00730000000",
          "new balance": "0.00730000000",
          "new average entry price": "",
          "trade price": "",
          "mark price": "",
          "funding rate": "-0.000023022168051861",
          "realized pnl": "",
          "fee": "0.00000000000",
          "realized funding": "0.00730000000",
          "collateral": "",
          "conversion spread percentage": "",
          "liquidation fee": "",
          "position uid": ""
        }
      },
      {
        "label": "futures liquidation",
        "count": 20,
        "row": {
          "uid": "97aa2ed2-f70a-4623-b332-ecd71a24a2bc",
          "dateTime": "2026-02-02 12:25:35",
          "account": "flex",
          "type": "futures liquidation",
          "symbol": "usd",
          "contract": "pf_suiusd",
          "change": "-7.18240000000",
          "new balance": "0.00000000000",
          "new average entry price": "",
          "trade price": "1.13490000000000000000",
          "mark price": "1.13413695874000000000",
          "funding rate": "-0.000007103617851910",
          "realized pnl": "-6.47820000000",
          "fee": "0.06700000000",
          "realized funding": "",
          "collateral": "",
          "conversion spread percentage": "",
          "liquidation fee": "0.63720000000",
          "position uid": ""
        }
      },
      {
        "label": "cross-exchange transfer",
        "count": 1,
        "row": {
          "uid": "62c6e18d-5e6b-4a54-b4db-4bf633624512",
          "dateTime": "2026-01-16 15:41:20",
          "account": "flex",
          "type": "cross-exchange transfer",
          "symbol": "eur",
          "contract": "",
          "change": "200.00000000000",
          "new balance": "200.00000000000",
          "new average entry price": "",
          "trade price": "",
          "mark price": "",
          "funding rate": "",
          "realized pnl": "",
          "fee": "",
          "realized funding": "",
          "collateral": "",
          "conversion spread percentage": "",
          "liquidation fee": "",
          "position uid": ""
        }
      }
    ]
  },
  {
    "source": "bit2me_spot_*.xlsx",
    "market": "spot",
    "typeColumn": "Tipo de operación",
    "headers": [
      "Tipo de operación",
      "Cantidad de destino",
      "Moneda de destino",
      "Cantidad de origen",
      "Moneda de origen",
      "Comisión de la operación",
      "Moneda de la comisión",
      "Exchange",
      "Grupo",
      "Descripción",
      "Fecha"
    ],
    "labels": [
      {
        "label": "Deposit",
        "count": 42,
        "row": {
          "Tipo de operación": "Deposit",
          "Cantidad de destino": "100",
          "Moneda de destino": "EUR",
          "Cantidad de origen": "100",
          "Moneda de origen": "EUR",
          "Comisión de la operación": "0",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "bank-transfer",
          "Descripción": "wallet fabdf995-32fb-4e39-af8d-1f95cb3445cb",
          "Fecha": "2024-12-02 16:26"
        }
      },
      {
        "label": "Trade",
        "count": 118,
        "row": {
          "Tipo de operación": "Trade",
          "Cantidad de destino": "37.636893",
          "Moneda de destino": "XRP",
          "Cantidad de origen": "100",
          "Moneda de origen": "EUR",
          "Comisión de la operación": "0.95",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "pocket",
          "Descripción": "wallet f741d952-b445-4331-a6f0-9eb956659dfb",
          "Fecha": "2024-12-02 22:37"
        }
      },
      {
        "label": "Staking",
        "count": 499,
        "row": {
          "Tipo de operación": "Staking",
          "Cantidad de destino": "0.0789135",
          "Moneda de destino": "B2M",
          "Cantidad de origen": "",
          "Moneda de origen": "",
          "Comisión de la operación": "0",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "earn",
          "Descripción": "earn 55dd75e8-d19f-4782-860d-95ba85116d3b",
          "Fecha": "2024-12-05 11:04"
        }
      },
      {
        "label": "Withdrawal",
        "count": 45,
        "row": {
          "Tipo de operación": "Withdrawal",
          "Cantidad de destino": "1.536429",
          "Moneda de destino": "HBAR",
          "Cantidad de origen": "2.236429",
          "Moneda de origen": "HBAR",
          "Comisión de la operación": "0.210620368",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "blockchain",
          "Descripción": "wallet b83277f8-77d5-4591-a47e-309e35b4b779 tx_hash:0.0.734891-1738248739-028188115",
          "Fecha": "2025-01-30 14:52"
        }
      },
      {
        "label": "Swap",
        "count": 1,
        "row": {
          "Tipo de operación": "Swap",
          "Cantidad de destino": "0.0084939",
          "Moneda de destino": "USDC",
          "Cantidad de origen": "0.0084939",
          "Moneda de origen": "USDT",
          "Comisión de la operación": "0",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "pocket",
          "Descripción": "wallet 59c197f8-8837-4c58-af95-4798fa561672",
          "Fecha": "2025-03-21 09:43"
        }
      },
      {
        "label": "Airdrop",
        "count": 1,
        "row": {
          "Tipo de operación": "Airdrop",
          "Cantidad de destino": "1778.08180605",
          "Moneda de destino": "B2M",
          "Cantidad de origen": "",
          "Moneda de origen": "",
          "Comisión de la operación": "0",
          "Moneda de la comisión": "EUR",
          "Exchange": "Bit2Me",
          "Grupo": "pocket",
          "Descripción": "wallet 7ac49abd-3e93-4b22-b778-a35c93848305",
          "Fecha": "2025-04-20 09:01"
        }
      }
    ]
  }
] as const;
